// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijnjikcbqswjgiejlzld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqbmppa2NicXN3amdpZWpsemxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTQ4NTEsImV4cCI6MjA2OTk3MDg1MX0.J681Vwi_YfRFF4vzrSRnXMerL_yW0-IN8k4CI2dl3Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});